export const TIPS_LOADING = 'TIPS_LOADING';
export const ADD_TIPS = 'ADD_TIPS';
export const TIPS_FAILED = 'TIPS_FAILED';

export const MUSIC_LOADING = 'MUSIC_LOADING';
export const ADD_MUSIC = 'ADD_MUSIC';
export const TIPS_MUSIC = 'MUSIC_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 
